import cv2
i1=cv2.imread('F:\Streamlit\Opencv_input\Genpact_logo.jpg',1)
cv2.imshow("Image Selected is ",i1)
cv2.waitKey(0)
print(i1)
print(i1.shape)
i11=cv2.imwrite("Genpact_logo.png",i1)
print(i1[550][730])
b,g,r =cv2.split(i1)
print("the b in the i1 is {}" ,b)
print("the g in the i1 is {}" ,g)
new_image = cv2.merge((b,g,r))
print(new_image.shape)
print(new_image)
cv2.imshow("Image Selected is now ",new_image)
cv2.waitKey(0)
ic1=new_image
dat=cv2.resize(ic1,(300,300),fx=.4,fy=3)
cv2.imshow("Image Selected is after modification ",dat)
cv2.waitKey(0)
dat_f1=cv2.flip(dat,0)
cv2.imshow("Image Selected is after horozontal flip ",dat_f1)
cv2.waitKey(0)
i1_line= cv2.line(dat,(10,10),(300,100),(0,0,255))
cv2.imshow("Image Selected is after adding line ",i1_line)
cv2.waitKey(0)
i1_circle=cv2.circle(dat,(200,200),(17),(0,255,10))
cv2.imshow("Image Selected is after adding line ",i1_circle)
cv2.waitKey(0)